### ISSUE TITLE
Use QSettings instead of data base for timer values

### ISSUE THREAD

**Issue by rweickelt** [tanghus/kitchen-timer-qml#12]
You created a wrapper for QSettings to store the program configuration and additionally, you use a database for the timers. Is there a special reason for that? The latter could be easily achieved though by using the array capabilities of QSettings. Would be worth a try and simplify the code, maybe.

**Comment by tanghus** [comment]
You're right. I was checking out solutions, so ended up with two ;)

But it works so I won't fix it until needed.
