### ISSUE TITLE
Enhancements for predefined timers

### ISSUE THREAD

**Issue by Ingvix** [tanghus/kitchen-timer-qml#13]
I think there's also enough space for 8th predefined timer. At least I would like to use that space so I don't think it would hurt to add it as you don't have to use it. 

Another idea that there also could be a left swipe menu where you could put a lot larger library of timers if needed. The up swipe menu could show the first 7 ( or imo 8) timers from that list.

**Comment by tanghus** [comment]
@Ingvix Sorry for the slight delay ;)
I have now made a menu that can be aligned left/right. I allows you for an unlimited amount of timers. It's not very elegant for now, but that will have to come later ;)
A new version will be updated as soon as translations are ready.
