### ISSUE TITLE
Update to 1.1.9.28/Eineheminlampi breaks the app.

### ISSUE THREAD

**Issue by jtts** [tanghus/kitchen-timer-qml#7]
Update to 1.1.9.28/Eineheminlampi breaks the app. The dial for setting the timer is missing.

**Comment by neversun** [comment]
You have to update your TimePicker component. See https://github.com/neversun/bodyweight-timer/commit/e0c4e06bbbb5d0d893ab90679a2395f4b5f6a601

**Comment by tanghus** [comment]
Thanks for the report. I've been afk for a week, so only just noticed it today when I updated.

Thanks for the link @neversun - I figured it was the ShaderEffect, but have never worked with any such things, so thanks for the copy/paste opportunity ;)

**Comment by neversun** [comment]
You're welcome!

**Comment by tanghus** [comment]
There is now a pre-release at https://github.com/tanghus/kitchen-timer-qml/releases/tag/v0.2.1-RC1

I'm putting it up at openrepos as well, but I'll wait with harbour until close to public release of SFOS 1.1.9
